[project]
name = "lantern"
version = "2.0.1"
description = "A handy terminal user interface (TUI) to manage leetcode solution indexes."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
